// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    Banner: typeof import('./src/components/Banner.vue')['default']
    DarkBtn: typeof import('./src/components/DarkBtn.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GoToTop: typeof import('./src/components/GoToTop.vue')['default']
    IconCibTypescript: typeof import('~icons/cib/typescript')['default']
    IconCiExternalLink: typeof import('~icons/ci/external-link')['default']
    IconCodiconMail: typeof import('~icons/codicon/mail')['default']
    IconEpArrowUpBold: typeof import('~icons/ep/arrow-up-bold')['default']
    IconIconoirGithub: typeof import('~icons/iconoir/github')['default']
    IconJamLinkedin: typeof import('~icons/jam/linkedin')['default']
    IconLineMdMoonFilled: typeof import('~icons/line-md/moon-filled')['default']
    IconLineMdSunnyFilled: typeof import('~icons/line-md/sunny-filled')['default']
    IconLogosBootstrap: typeof import('~icons/logos/bootstrap')['default']
    IconLogosDockerIcon: typeof import('~icons/logos/docker-icon')['default']
    IconLogosExpress: typeof import('~icons/logos/express')['default']
    IconLogosFirebase: typeof import('~icons/logos/firebase')['default']
    IconLogosGitIcon: typeof import('~icons/logos/git-icon')['default']
    IconLogosJavascript: typeof import('~icons/logos/javascript')['default']
    IconLogosSass: typeof import('~icons/logos/sass')['default']
    IconLogosTailwindcssIcon: typeof import('~icons/logos/tailwindcss-icon')['default']
    IconLogosVue: typeof import('~icons/logos/vue')['default']
    IconLucideCodepen: typeof import('~icons/lucide/codepen')['default']
    Projects: typeof import('./src/components/Projects.vue')['default']
    SkillSet: typeof import('./src/components/SkillSet.vue')['default']
  }
}
