// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    Banner: typeof import('./src/components/Banner.vue')['default']
    copy: typeof import('./src/components/Skills copy.vue')['default']
    DarkBtn: typeof import('./src/components/DarkBtn.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    IconCibTypescript: typeof import('~icons/cib/typescript')['default']
    IconCiExternalLink: typeof import('~icons/ci/external-link')['default']
    IconEmojioneCrescentMoon: typeof import('~icons/emojione/crescent-moon')['default']
    IconFa6BrandsSass: typeof import('~icons/fa6-brands/sass')['default']
    IconFluentemojiSun: typeof import('~icons/fluent/emoji-sun')['default']
    IconFluentEmojiSun: typeof import('~icons/fluent/emoji-sun')['default']
    IconIconoirGithub: typeof import('~icons/iconoir/github')['default']
    IconLineMdMoon: typeof import('~icons/line-md/moon')['default']
    IconLineMdMoonFilled: typeof import('~icons/line-md/moon-filled')['default']
    IconLineMdSunnyFilled: typeof import('~icons/line-md/sunny-filled')['default']
    IconLogosJavascript: typeof import('~icons/logos/javascript')['default']
    IconLogosSass: typeof import('~icons/logos/sass')['default']
    IconLogosTypescript: typeof import('~icons/logos/typescript')['default']
    IconLogosTypescriptIcon: typeof import('~icons/logos/typescript-icon')['default']
    IconLogosVue: typeof import('~icons/logos/vue')['default']
    IconTwemojiCrescentMoon: typeof import('~icons/twemoji/crescent-moon')['default']
    IconTwemojiSun: typeof import('~icons/twemoji/sun')['default']
    Projects: typeof import('./src/components/Projects.vue')['default']
    Skills: typeof import('./src/components/Skills.vue')['default']
    SkillSet: typeof import('./src/components/SkillSet.vue')['default']
  }
}
